# Generated by Django 3.1.3 on 2021-01-06 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210106_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile3.png', null=True, upload_to=''),
        ),
    ]
